/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Motorcycle } from './types';

export const MOTORCYCLES: Motorcycle[] = [
  {
    id: 'sport-1',
    nameAr: 'كاواساكي نينجا H2R',
    nameEn: 'Kawasaki Ninja H2R',
    brandAr: 'كاواساكي',
    brandEn: 'Kawasaki',
    category: 'sport',
    price: 245000,
    condition: 'new',
    year: 2026,
    mileage: 0,
    engineSize: 998,
    power: 310,
    weight: 216,
    fuelCapacity: 17,
    colorAr: 'أسود مرآة مع أخضر معدني',
    colorEn: 'Mirror Coated Black with Lime Green',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'تحفة هندسية فائقة الشحن. تمثل نينجا H2R قمة التطور التقني وجنون القوة لشركة كاواساكي، وتعد أسرع دراجة نارية إنتاجية في العالم.',
    descriptionEn: 'The supercharged engineering masterpiece. The Ninja H2R represents the pinnacle of Kawasaki\'s technical development and forced-induction raw power, making it the fastest production motorcycle on earth.',
    keySpecsAr: ['محرك سوبرتشارج رباعي الأسطوانات', 'جناح هوائي ديناميكي من ألياف الكربون', 'نظام فحمات بريمبو Brembo Stylema', 'شاشة TFT ملونة مع اتصال للهاتف'],
    keySpecsEn: ['Supercharged 4-cylinder engine', 'Carbon fiber aerodynamic winglets', 'Brembo Stylema brake calipers', 'Full color TFT dashboard with smartphone connectivity'],
    featured: true,
    qty: 1
  },
  {
    id: 'sport-2',
    nameAr: 'ياماها YZF-R1M',
    nameEn: 'Yamaha YZF-R1M',
    brandAr: 'ياماها',
    brandEn: 'Yamaha',
    category: 'sport',
    price: 112000,
    condition: 'new',
    year: 2025,
    mileage: 0,
    engineSize: 998,
    power: 200,
    weight: 202,
    fuelCapacity: 17,
    colorAr: 'كربون وفضي معدني',
    colorEn: 'Carbon Fiber / Silver Blu',
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'مستوحاة مباشرة من دراجة سباق MotoGP. تم تزويد R1M بهيكل كربوني كامل وبنظام تعليق إلكتروني أوهلينز لتقديم تجربة قيادة ساحرة على المضمار.',
    descriptionEn: 'Straight out of Moto GP racing heritage. The R1M features full carbon fiber bodywork and Öhlins Electronic Racing Suspension for the ultimate track experience.',
    keySpecsAr: ['محرك رباعي متعامد الكرنك Crossplane', 'نظام تعليق إلكتروني Öhlins ERS', 'هيكل خارجي كامل من ألياف الكربون', 'وحدة قياس تفاعلية IMU بستة محاور'],
    keySpecsEn: ['Crossplane 4-cylinder engine', 'Öhlins Electronic Racing Suspension', 'Full carbon fiber bodywork', '6-axis Inertial Measurement Unit (IMU)'],
    featured: true,
    qty: 2
  },
  {
    id: 'sport-3',
    nameAr: 'دوكاتي بانيجالي V4 S',
    nameEn: 'Ducati Panigale V4 S',
    brandAr: 'دوكاتي',
    brandEn: 'Ducati',
    category: 'sport',
    price: 138000,
    condition: 'used',
    year: 2024,
    mileage: 4200,
    engineSize: 1103,
    power: 215,
    weight: 195,
    fuelCapacity: 16,
    colorAr: 'أحمر دوكاتي الكلاسيكي',
    colorEn: 'Ducati Red',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'قمة الشغف والهندسة الإيطالية. نظيفة جداً وخالية من الحوادث، تمت الصيانة الدورية في وكالة دوكاتي الرسمية. جاهزة تماماً للقيادة الفائقة.',
    descriptionEn: 'The absolute summit of Italian passion and premium engineering. Pristine condition with no accidents, full service history at official Ducati dealership.',
    keySpecsAr: ['محرك Desmosedici Stradale V4', 'طقم تعليق ذكي Ohlins Smart EC 2.0', 'جنوط ألومنيوم مطروقة خفيفة الوزن', 'عادم سباق Akrapovič اختياري'],
    keySpecsEn: ['Desmosedici Stradale V4 engine', 'Ohlins Smart EC 2.0 active suspension', 'Lightweight forged aluminum wheels', 'Premium Akrapovič racing exhaust pre-installed'],
    featured: false,
    qty: 1
  },
  {
    id: 'cruiser-1',
    nameAr: 'هارلي ديفيدسون فت بوي 114',
    nameEn: 'Harley-Davidson Fat Boy 114',
    brandAr: 'هارلي ديفيدسون',
    brandEn: 'Harley-Davidson',
    category: 'cruiser',
    price: 98000,
    condition: 'new',
    year: 2026,
    mileage: 0,
    engineSize: 1868,
    power: 94,
    weight: 317,
    fuelCapacity: 19,
    colorAr: 'كروم لامع مع رذاذ سائل',
    colorEn: 'Vivid Black / Bright Chrome',
    image: 'https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'الأيقونة الأصلية ذات الهيبة المهيبة. عجلات Lakester صلبة من الألمنيوم، إضاءة LED ساطعة، وهيكل خلفي منخفض عريض يعطيك هيبة لا مثيل لها على الطريق.',
    descriptionEn: 'The original fat custom icon. Featuring solid-disc Lakester aluminum wheels, brilliant Signature LED headlamps, and steamroller stance for dominant road presence.',
    keySpecsAr: ['محرك Milwaukee-Eight 114 هائل العزم', 'جنوط Lakester مسبوكة صلبة ومميزة', 'نظام تعليق خلفي أحادي المساعد مخفي', 'عزم دوران جبار يبلغ 155 نيوتن متر'],
    keySpecsEn: ['Milwaukee-Eight 114 V-Twin engine', 'Signature Solid Lakester aluminum wheels', 'Hidden monoshock rear suspension', 'Massive 155 Nm of torque at low RPM'],
    featured: true,
    qty: 3
  },
  {
    id: 'cruiser-2',
    nameAr: 'هوندا ريبيل 500',
    nameEn: 'Honda Rebel 500',
    brandAr: 'هوندا',
    brandEn: 'Honda',
    category: 'cruiser',
    price: 29500,
    condition: 'new',
    year: 2025,
    mileage: 0,
    engineSize: 471,
    power: 46,
    weight: 191,
    fuelCapacity: 11,
    colorAr: 'رمادي غير لامع فضائي',
    colorEn: 'Matte Armored Silver',
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'أفضل دراجة كروزر للمبتدئين والقيادة اليومية. مقعد منخفض ومريح للغاية، وزن مقالي متوازن وسلِم قيادة يسير.',
    descriptionEn: 'The ultimate cruiser for beginners and urban riders. Very low seat height, manageable weight, and highly reliable parallel twin-cylinder engine make it exceptionally easy to ride.',
    keySpecsAr: ['محرك ثنائي الأسطوانات متوازي تبريد سائل', 'ارتفاع منخفض للمقعد 690 ملم فقط', 'كلتش مساند مانع للانزلاق Slip & Assist', 'إضاءات LED دائرية كلاسيكية حديثة'],
    keySpecsEn: ['Liquid-cooled parallel-twin engine', 'Ultra-low seat height of just 690mm', 'Slipper/assist clutch for smoother shifts', 'Classic round LED multi-bulb Headlight'],
    featured: false,
    qty: 5
  },
  {
    id: 'adventure-1',
    nameAr: 'بي إم دبليو R 1300 GS',
    nameEn: 'BMW R 1300 GS Option 719',
    brandAr: 'بي إم دبليو',
    brandEn: 'BMW',
    category: 'adventure',
    price: 129000,
    condition: 'new',
    year: 2026,
    mileage: 0,
    engineSize: 1300,
    power: 145,
    weight: 237,
    fuelCapacity: 19,
    colorAr: 'ذهبي ملوكي مع أخضر معدني',
    colorEn: 'Option 719 Aurelius Green Metallic',
    image: 'https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'أعجوبة المغامرات الجديدة كلياً من BMW. دراجة أخف وزناً بـ 12 كجم من الجيل السابق، ومزودة بالمزيد من القوة والتكنولوجيا الذكية لعبور القارات بمتعة فائقة.',
    descriptionEn: 'The all-new ultimate adventure touring machine. Lighter by 12kg than its predecessor, packing more displacement, boxer power, and advanced suspension to conquer any terrain with luxury.',
    keySpecsAr: ['محرك بوكسر متطور مع نظام ShiftCam', 'نظام رادار ذكي أمامي وخلفي لحفظ المسافة', 'تحكم تعليق ديناميكي إلكتروني EVO Telelever', 'شاشة عرض TFT قياس 6.5 بوصة ملاحة'],
    keySpecsEn: ['Boxer-twin engine with ShiftCam technology', 'Front and rear safety radar with active Cruise Control', 'EVO Telelever electronic dynamic suspension', 'Premium 6.5-inch TFT console with Navigation'],
    featured: true,
    qty: 2
  },
  {
    id: 'adventure-2',
    nameAr: 'هوندا أفريكا توين CRF1100L',
    nameEn: 'Honda Africa Twin CRF1100L',
    brandAr: 'هوندا',
    brandEn: 'Honda',
    category: 'adventure',
    price: 68000,
    condition: 'used',
    year: 2024,
    mileage: 12000,
    engineSize: 1084,
    power: 101,
    weight: 226,
    fuelCapacity: 18.8,
    colorAr: 'ثلاثي الألوان (أحمر، أبيض، أزرق)',
    colorEn: 'Grand Prix Red HRC Tricolor',
    image: 'https://images.unsplash.com/photo-1591637333036-79c833446df9?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'قاهرة الكثبان الرملية والدروب البرية. مجهزة بناقل حركة DCT الأوتوماتيكي المزدوج لراحة وتجاوب منقطع النظير في السفر والبر.',
    descriptionEn: 'The desert conqueror. Equipped with Honda\'s famous Dual Clutch Transmission (DCT) for seamless automatic shifting over dunes and rugged trails.',
    keySpecsAr: ['ناقل حركة DCT أوتوماتيكي ثنائي الكلتش', 'شاشة مع دعم Apple CarPlay & Android Auto', 'نظام تحرك بستة مستويات عزم HSTC', 'شنط خلفية ألومنيوم أصلية مدمجة'],
    keySpecsEn: ['Automatic Dual Clutch Transmission (DCT)', 'Touchscreen with Apple CarPlay & Android Auto support', 'Multi-level Honda Selectable Torque Control (HSTC)', 'Pre-fitted official aluminum rugged panniers'],
    featured: false,
    qty: 1
  },
  {
    id: 'scooter-1',
    nameAr: 'فيسبا بريميفيرا 150',
    nameEn: 'Vespa Primavera 150 Picnic Edition',
    brandAr: 'فيسبا',
    brandEn: 'Vespa',
    category: 'scooter',
    price: 24000,
    condition: 'new',
    year: 2025,
    mileage: 0,
    engineSize: 155,
    power: 13,
    weight: 115,
    fuelCapacity: 8,
    colorAr: 'بيج كلاسيكي مع عاجي وسلة خوص رفيعة',
    colorEn: 'Beige Picnic Classic with rattan basket',
    image: 'https://images.unsplash.com/photo-1515787366009-7cbdd2dc587b?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'الأناقة الإيطالية والروح الإبداعية مجسدة في سكوتر عصري رائع للتنقلات الممتعة في المدينة والنزهات الفاخرة.',
    descriptionEn: 'The quintessential Italian style and creative spirit, packaged in a charming, modern scooter perfect for stylish urban commuting and leisurely luxury escapes.',
    keySpecsAr: ['محرك i-get اقتصادي صديق للبيئة وسلس جداً', 'فرامل ABS متطورة على العجلة الأمامية', 'سلة خوص كلاسيكية خلفية فريدة للنزهات', 'منفذ شحن USB للموبايل مخفي بالصندوق'],
    keySpecsEn: ['Eco-friendly i-get engine, ultra quiet and smooth', 'Single-channel front wheel ABS safety', 'Unique authentic rear rattan basket setup', 'Handy glove-box integrated USB phone charging port'],
    featured: false,
    qty: 4
  },
  {
    id: 'scooter-2',
    nameAr: 'ياماها تي ماكس 560 Tech MAX',
    nameEn: 'Yamaha TMAX 560 Tech MAX',
    brandAr: 'ياماها',
    brandEn: 'Yamaha',
    category: 'scooter',
    price: 54000,
    condition: 'new',
    year: 2026,
    mileage: 0,
    engineSize: 562,
    power: 48,
    weight: 220,
    fuelCapacity: 15,
    colorAr: 'رمادي صلب داكن',
    colorEn: 'Dark Petrol Matte',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'سوبر سكوتر رياضي خارق للمسافات البعيدة والقيادة اليومية الحماسية. مريح مثل الليموزين وسريع مثل الدراجات الرياضية.',
    descriptionEn: 'The high-performance maxi-scooter. Combining motorcycle-grade chassis and power with cruising-style comfort, complete with heated seats and electronic screen.',
    keySpecsAr: ['محرك قوي ثنائي الأسطوانات 562 سي سي', 'زجاج أمامي قابل للتعديل كهربائياً بمفتاح', 'مقود ومقاعد بخاصية التدفئة للشتاء', 'تشغيل ذكي بدون مفتاح Smart Key'],
    keySpecsEn: ['Powerful 562cc twin-cylinder engine', 'Electronically adjustable flyscreen', 'Heated rider seat and comfortable handgrips', 'Keyless Smart Key ignition system'],
    featured: true,
    qty: 2
  },
  {
    id: 'naked-1',
    nameAr: 'دوكاتي مونستر SP',
    nameEn: 'Ducati Monster SP',
    brandAr: 'دوكاتي',
    brandEn: 'Ducati',
    category: 'naked',
    price: 79000,
    condition: 'new',
    year: 2025,
    mileage: 0,
    engineSize: 937,
    power: 111,
    weight: 186,
    fuelCapacity: 14,
    colorAr: 'تلوين سباق دوكاتي الرسمي (أحمر وأسود)',
    colorEn: 'MotoGP-inspired livery Red & Black',
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'خفيفة الوزن، رشيقة ومرحة للغاية. فئة SP تمنحك تعليق أوهلينز سباقي متقدم ونظام مكابح بريمبو فائق القوة لمتعة قصوى في المنعطفات.',
    descriptionEn: 'Light, compact, and incredibly fun. The SP version takes the famous Monster up a notch with premium Öhlins adjustable suspension and track-proven Brembo brakes.',
    keySpecsAr: ['محرك Testastretta 11° متجاوب', 'مساعدين أمامية Öhlins ذهبية بالكامل', 'عادم Termignoni رياضي مزدوج معتمد', 'وزن شديد الخفة وهيكل ألومنيوم ذكي'],
    keySpecsEn: ['Punchy Testastretta 11-degree L-twin engine', 'Premium gold Öhlins fully adjustable forks', 'Homologated dual Termignoni slip-on silencers', 'Aluminum front frame inspired by Panigale V4'],
    featured: true,
    qty: 1
  },
  {
    id: 'naked-2',
    nameAr: 'هوندا CB650R كافيه ريسر',
    nameEn: 'Honda CB650R Neo Sports Cafe',
    brandAr: 'هوندا',
    brandEn: 'Honda',
    category: 'naked',
    price: 36000,
    condition: 'used',
    year: 2023,
    mileage: 8400,
    engineSize: 649,
    power: 94,
    weight: 202,
    fuelCapacity: 15.4,
    colorAr: 'أسود مع برونز معدني',
    colorEn: 'Matte Gunpowder Black Metallic',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800&h=600',
    descriptionAr: 'تصميم يمزج عراقة الماضي بتكنولوجيا المستقبل (Neo Sports Café). محرك رائع بأربع أسطوانات صوته طرب للمسامع.',
    descriptionEn: 'Beautiful retro-modern Neo Sports Café design. Driven by a super smooth inline 4-cylinder engine that sounds absolutely musical as you rev it through redline.',
    keySpecsAr: ['محرك طربي رباعي الأسطوانات تبريد سائل', 'مساعد شوا Showa SFF-BP عالي التماسك', 'شاشة عرض LCD واضحة ومقود عريض ومريح', 'نظام تحكم بالتماسك HSTC للأمان المتقدم'],
    keySpecsEn: ['Smooth screaming inline 4-cylinder engine', 'High-quality Showa SFF-BP inverted forks', 'Neo-retro circular LED headlight design', 'Honda Selectable Torque Control (HSTC) traction control'],
    featured: false,
    qty: 2
  }
];

export const CATEGORIES = [
  { id: 'all', nameAr: 'الكل', nameEn: 'All' },
  { id: 'sport', nameAr: 'رياضية (ريس)', nameEn: 'Sport' },
  { id: 'cruiser', nameAr: 'كروزر وكلاسيك', nameEn: 'Cruiser' },
  { id: 'adventure', nameAr: 'مغامرات وجبلي', nameEn: 'Adventure' },
  { id: 'scooter', nameAr: 'سكوتر', nameEn: 'Scooter' },
  { id: 'naked', nameAr: 'رياضية مكشوفة (نيكد)', nameEn: 'Naked Street' }
];

export const BRANDS = ['كاواساكي', 'ياماها', 'دوكاتي', 'هارلي ديفيدسون', 'هوندا', 'بي إم دبليو', 'فيسبا'];

export const BRAND_MAP: Record<string, string> = {
  'كاواساكي': 'Kawasaki',
  'ياماها': 'Yamaha',
  'دوكاتي': 'Ducati',
  'هارلي ديفيدسون': 'Harley-Davidson',
  'هوندا': 'Honda',
  'بي إم دبليو': 'BMW',
  'فيسبا': 'Vespa'
};
